### ISSUE TITLE
[swiss search] ch.astra.wanderland-sperrungen_umleitungen layer not found in some cases

### ISSUE THREAD

**Issue by consta-v** [geoadmin/service-sphinxsearch#429] opened 2020-07-28 14:32 UTC
UC: Open app (Edge, Chrome), clear cache and reload app, change language to french, search for "randonn"
Result: The layer "Fermetures Chemins de randonnée" doesn't appear in the result list. It appears only if I search for "randonnée" (complete word)
Expected: the layer can be found with this search

**Comment by ltclm** [comment] 2020-08-11 08:11
cant reproduce:
https://api3.geo.admin.ch/2005271117/rest/services/ech/SearchServer?sr=2056&searchText=randonn&lang=fr&type=layers first hit is ch.astra.wanderland-sperrungen_umleitungen

**Comment by boecklic** [comment] 2020-08-11 12:25
this case (search string is `randoné`) doesn't work: https://api3.geo.admin.ch/2005271117/rest/services/ech/SearchServer?sr=2056&searchText=randonn%C3%A9&lang=fr&type=layers

**Comment by boecklic** [comment] 2020-08-11 12:29
But this case works: https://api3.geo.admin.ch/rest/services/ech/SearchServer?sr=2056&searchText=randonn%C3%A9&lang=fr&type=layers

Issue is not related to search, but to CF, won't fix for the moment, will be reevaluated once CF is removed in front of api3

**Closed** 2020-08-11 12:29 UTC
